POST http://localhost:8081/order
Content-Type: application/json

{
  "market": "KRW-BTC",
  "side": "BUY",
  "amount": 10000
}

###

GET http://localhost:8081/orders

###

GET http://localhost:8081/orders/999

###
PATCH http://localhost:8081/orders/1/ordered

